export const FETCH_OVERVIEW_MAP_DATA = 'yojee/maps/FETCH_OVERVIEW_MAP_DATA'
export const FETCH_OVERVIEW_MAP_DATA_SUCCESS = 'yojee/maps/FETCH_OVERVIEW_MAP_DATA_SUCCESS'
export const FETCH_OVERVIEW_MAP_DATA_FAILED = 'yojee/maps/FETCH_OVERVIEW_MAP_DATA_FAILED'

export const UPDATE_ROUTE_TO_FIRST_WAYPOINT = 'yojee/maps/UPDATE_ROUTE_TO_FIRST_WAYPOINT'
export const UPDATE_ROUTE_TO_FIRST_WAYPOINT_SUCCESS = 'yojee/maps/UPDATE_ROUTE_TO_FIRST_WAYPOINT_SUCCESS'
export const UPDATE_ROUTE_TO_FIRST_WAYPOINT_FAILED = 'yojee/maps/UPDATE_ROUTE_TO_FIRST_WAYPOINT_FAILED'
