export const SHOW_INCOMING_TASKGROUPS_POPUP =
  'yojee/task/incoming/SHOW_INCOMING_TASKGROUPS_POPUP'
export const HIDE_INCOMING_TASKGROUPS_POPUP =
  'yojee/task/incoming/HIDE_INCOMING_TASKGROUPS_POPUP'
export const FECTH_INCOMING_TASKGROUPS =
  'yojee/task/incoming/FECTH_INCOMING_TASKGROUPS'
export const FECTH_INCOMING_TASKGROUPS_SUCCESS =
  'yojee/task/incoming/FECTH_INCOMING_TASKGROUPS_SUCCESS'
export const FECTH_INCOMING_TASKGROUPS_FAILED =
  'yojee/task/incoming/FECTH_INCOMING_TASKGROUPS_FAILED'
export const ACCEPT_TASKGROUPS = 'yojee/task/incoming/ACCEPT_TASKGROUPS'
export const ACCEPT_TASKGROUPS_SUCCESS =
  'yojee/task/incoming/ACCEPT_TASKGROUPS_SUCCESS'
export const ACCEPT_TASKGROUPS_FAILED =
  'yojee/task/incoming/ACCEPT_TASKGROUPS_FAILED'
export const REJECT_TASKGROUPS = 'yojee/task/incoming/REJECT_TASKGROUPS'
export const REJECT_TASKGROUPS_SUCCESS =
  'yojee/task/incoming/REJECT_TASKGROUPS_SUCCESS'
export const REJECT_TASKGROUPS_FAILED =
  'yojee/task/incoming/REJECT_TASKGROUPS_FAILED'
export const SET_CURRENT_TASKGROUP = 'yojee/task/incoming/SET_CURRENT_TASKGROUP'
