export const FCM_RECEIVED_TOKEN = 'yojee/fcm/FCM_RECEIVED_TOKEN'
export const FCM_REGISTER_TOKEN_SUCCESS = 'yojee/fcm/FCM_REGISTER_TOKEN_SUCCESS'
export const FCM_REGISTER_TOKEN_FAILED = 'yojee/fcm/FCM_REGISTER_TOKEN_FAILED'
export const FCM_RECEIVED_MESSAGE = 'yojee/fcm/FCM_RECEIVED_MESSAGE'

export const HANDLE_SINGLE_FCM_EVENT = 'yojee/fcm/HANDLE_SINGLE_FCM_EVENT'
export const HANDLE_SINGLE_FCM_EVENT_FAILED =
  'yojee/fcm/HANDLE_SINGLE_FCM_EVENT_FAILED'
