export const GET_USERINFO_REQUEST = 'yojee/user/GET_USERINFO_REQUEST'
export const GET_USERINFO_SUCCESS = 'yojee/user/GET_USERINFO_SUCCESS'
export const GET_USERINFO_FAILED = 'yojee/user/GET_USERINFO_FAILED'
