export const UPDATE_USER_INFO = 'yojee/user/UPDATE_USER_INFO'
export const CHANGE_STATUS = 'yojee/user/CHANGE_STATUS'
export const CHANGE_DELIVERY_TYPE = 'yojee/user/CHANGE_DELIVERY_TYPE'

export const DRIVER_STATUS_OFF_DUTY = 'DRIVER_STATUS_OFF_DUTY'
export const DRIVER_STATUS_PROBLEM = 'DRIVER_STATUS_PROBLEM'
export const DRIVER_STATUS_EMERGENCY = 'DRIVER_STATUS_EMERGENCY'
export const DRIVER_STATUS_NORMAL = 'DRIVER_STATUS_NORMAL'
export const DRIVER_STATUS_IDLE = 'DRIVER_STATUS_IDLE'
export const DRIVER_STATUS_IN_DELIVERY = 'DRIVER_STATUS_IN_DELIVERY'

export const DriverStatus = [
  DRIVER_STATUS_NORMAL,
  DRIVER_STATUS_IDLE,
  DRIVER_STATUS_IN_DELIVERY,
  DRIVER_STATUS_OFF_DUTY,
  DRIVER_STATUS_PROBLEM,
  DRIVER_STATUS_EMERGENCY,
]
