import { NavigationActions } from 'react-navigation'

export const STARTUP = 'yojee/app/STARTUP'

export const DO_ON_LOGGED_REQUEST = 'yojee/app/DO_ON_LOGGED_REQUEST'
export const DO_ON_LOGGED_SUCCESS = 'yojee/app/DO_ON_LOGGED_SUCCESS'
export const DO_ON_LOGGED_FAILED = 'yojee/app/DO_ON_LOGGED_FAILED'

export const PERMISSION_CHECK_REQUEST = 'yojee/app/PERMISSION_CHECK_REQUEST'
export const PERMISSION_CHECK_SUCCESS = 'yojee/app/PERMISSION_CHECK_SUCCESS'
export const PERMISSION_CHECK_FAILED = 'yojee/app/PERMISSION_CHECK_FAILED'

export const CHECK_BINARY_VERSION_REQUEST =
  'yojee/app/CHECK_BINARY_VERSION_REQUEST'
export const CHECK_BINARY_VERSION_SUCCESS =
  'yojee/app/CHECK_BINARY_VERSION_SUCCESS'
export const CHECK_BINARY_VERSION_FAILED =
  'yojee/app/CHECK_BINARY_VERSION_FAILED'

export const CHECK_IF_USER_LOGGED_REQUEST =
  'yojee/app/CHECK_IF_USER_LOGGED_REQUEST'
export const CHECK_IF_USER_LOGGED_SUCCESS =
  'yojee/app/CHECK_IF_USER_LOGGED_SUCCESS'
export const CHECK_IF_USER_LOGGED_FAILED =
  'yojee/app/CHECK_IF_USER_LOGGED_FAILED'

export const GET_COMPANY_CONFIGURATION_REQUEST =
  'yojee/app/GET_COMPANY_CONFIGURATION_REQUEST'
export const GET_COMPANY_CONFIGURATION_SUCCESS =
  'yojee/app/GET_COMPANY_CONFIGURATION_SUCCESS'
export const GET_COMPANY_CONFIGURATION_FAILED =
  'yojee/app/GET_COMPANY_CONFIGURATION_FAILED'

export const MARK_DELIVERY_FAIL_REQUEST = 'yojee/app/MARK_DELIVERY_FAIL_REQUEST'
export const MARK_DELIVERY_FAIL_SUCCESS = 'yojee/app/MARK_DELIVERY_FAIL_SUCCESS'
export const MARK_DELIVERY_FAIL_FAILED = 'yojee/app/MARK_DELIVERY_FAIL_FAILED'

export const ON_NEW_JOB_COMMING = 'yojee/app/ON_NEW_JOB_COMMING'

export const MARK_NEED_RESUME_STARTUP_CODE =
  'yojee/app/MARK_NEED_RESUME_STARTUP_CODE'
export const MARK_NEED_RESUME_STARTUP_CODE_SUCCESS =
  'yojee/app/MARK_NEED_RESUME_STARTUP_CODE_SUCCESS'

export const APP_INITIALIZED = 'yojee/app/APP_INITIALIZED'

export const NETWORK_CHANGE = 'yojee/app/NETWORK_CHANGE'

export const INIT_LOCATION_REQUEST = 'yojee/app/INIT_LOCATION_REQUEST'
export const INIT_LOCATION_SUCCESS = 'yojee/app/INIT_LOCATION_SUCCESS'
export const INIT_LOCATION_FAILED = 'yojee/app/INIT_LOCATION_FAILED'

export const PERSIST_REHYDRATE = 'persist/REHYDRATE'

export const ON_APP_GO_TO_FOREGROUND = 'yojee/app/ON_APP_GO_TO_FOREGROUND'

export const { NAVIGATE, BACK, RESET } = NavigationActions

export const REPLACE = 'Navigations/REPLACE'
