export const FETCH_CONVERSATION_REQUEST =
  'yojee/chat/FETCH_CONVERSATION_REQUEST'
export const FETCH_CONVERSATION_SUCCESS =
  'yojee/chat/FETCH_CONVERSATION_SUCCESS'
export const FETCH_CONVERSATION_FAILED = 'yojee/chat/FETCH_CONVERSATION_FAILED'

export const CHAT_LOGIN_REQUEST = 'yojee/chat/CHAT_LOGIN_REQUEST'
export const CHAT_LOGIN_SUCCESS = 'yojee/chat/CHAT_LOGIN_SUCCESS'
export const CHAT_LOGIN_FAILED = 'yojee/chat/CHAT_LOGIN_FAILED'

export const HANDLE_NEW_CHAT_COMMING_REQUEST =
  'yojee/chat/HANDLE_NEW_CHAT_COMMING_REQUEST'
export const HANDLE_NEW_CHAT_COMMING_SUCCESS =
  'yojee/chat/HANDLE_NEW_CHAT_COMMING_SUCCESS'
export const HANDLE_NEW_CHAT_COMMING_FAILED =
  'yojee/chat/HANDLE_NEW_CHAT_COMMING_FAILED'
