export const FETCH_PROFILE_STATS = 'yojee/profile/FETCH_PROFILE_STATS'
export const FETCH_PROFILE_STATS_SUCCESS =
  'yojee/profile/FETCH_PROFILE_STATS_SUCCESS'
export const FETCH_PROFILE_STATS_FAILED =
  'yojee/profile/FETCH_PROFILE_STATS_FAILED'

export const UPLOAD_PROFILE_AVATAR = 'yojee/profile/UPLOAD_PROFILE_AVATAR'
export const UPLOAD_PROFILE_AVATAR_SUCCESS =
  'yojee/profile/UPLOAD_PROFILE_AVATAR_SUCCESS'
export const UPLOAD_PROFILE_AVATAR_FAILED =
  'yojee/profile/UPLOAD_PROFILE_AVATAR_FAILED'

export const UPDATE_DUTY_STATUS = 'yojee/profile/UPDATE_DUTY_STATUS'
export const UPDATE_DUTY_STATUS_SUCCESS =
  'yojee/profile/UPDATE_DUTY_STATUS_SUCCESS'
export const UPDATE_DUTY_STATUS_FAILED =
  'yojee/profile/UPDATE_DUTY_STATUS_FAILED'

export const FORCE_VEHICLE_SELECT = 'yojee/profile/FORCE_VEHICLE_SELECT'
export const FORCE_VEHICLE_SELECT_SUCCESS =
  'yojee/profile/FORCE_VEHICLE_SELECT_SUCCESS'
export const FORCE_VEHICLE_SELECT_FAILED =
  'yojee/profile/FORCE_VEHICLE_SELECT_FAILED'

export const SELECT_VEHICLE = 'yojee/profile/SELECT_VEHICLE'
export const SELECT_VEHICLE_SUCCESS = 'yojee/profile/SELECT_VEHICLE_SUCCESS'
export const SELECT_VEHICLE_FAILED = 'yojee/profile/SELECT_VEHICLE_FAILED'
