export const REQUEST_LOG_REQUEST = 'yojee/cjf/REQUEST_LOG_REQUEST'
export const REQUEST_LOG_SUCCESS = 'yojee/cjf/REQUEST_LOG_SUCCESS'
export const REQUEST_LOG_FAILED = 'yojee/cjf/REQUEST_LOG_FAILED'

export const CHECKING_CONDITIONS_REQUEST =
  'yojee/cjf/CHECKING_CONDITIONS_REQUEST'
export const CHECKING_CONDITIONS_SUCCESS =
  'yojee/cjf/CHECKING_CONDITIONS_SUCCESS'
export const CHECKING_CONDITIONS_FAILED = 'yojee/cjf/CHECKING_CONDITIONS_FAILED'

export const SAVE_IMAGE_TO_DISK_REQUEST = 'yojee/cjf/SAVE_IMAGE_TO_DISK_REQUEST'
export const SAVE_IMAGE_TO_DISK_SUCCESS = 'yojee/cjf/SAVE_IMAGE_TO_DISK_SUCCESS'
export const SAVE_IMAGE_TO_DISK_FAILED = 'yojee/cjf/SAVE_IMAGE_TO_DISK_FAILED'

export const REMOVE_IMAGE_FROM_DISK_REQUEST =
  'yojee/cjf/REMOVE_IMAGE_FROM_DISK_REQUEST'
export const REMOVE_IMAGE_FROM_DISK_SUCCESS =
  'yojee/cjf/REMOVE_IMAGE_FROM_DISK_SUCCESS'
export const REMOVE_IMAGE_FROM_DISK_FAILED =
  'yojee/cjf/REMOVE_IMAGE_FROM_DISK_FAILED'

export const SET_CURRENT_CONDITION = 'yojee/cjf/SET_CURRENT_CONDITION'
export const ALL_JOB_REQUESTS_LOGGED = 'yojee/cif/ALL_JOB_REQUESTS_LOGGED'

export const PHOTO_CAPTURED = 'yojee/cif/PHOTO_CAPTURED'

export const SYNCING_DEAMON_REQUEST = 'yojee/cif/SYNCING_DEAMON_REQUEST'
export const SYNCING_DEAMON_START = 'yojee/cif/SYNCING_DEAMON_START'
export const SYNCING_DEAMON_STOP = 'yojee/cif/SYNCING_DEAMON_STOP'
export const SYNCING_DEAMON_FAIL = 'yojee/cif/SYNCING_DEAMON_FAIL'

export const SYNCING_AN_ACTION_SUCCESS = 'yojee/cif/SYNCING_AN_ACTION_SUCCESS'
export const SYNCING_AN_ACTION_FAILED = 'yojee/cif/SYNCING_AN_ACTION_FAILED'

export const MARK_A_DELIVERY_AS_DEX = 'yojee/cif/MARK_A_DELIVERY_AS_DEX'

export const UPDATE_RECIPIENT = 'yojee/cif/UPDATE_RECIPIENT'

export const REMOVE_A_JOB_QUEUE = 'yojee/cif/REMOVE_A_JOB_QUEUE'

export const SYNC_UPLOAD_IMAGE_AS_POD_SUCCESS =
  'yojee/cjf/SYNC_UPLOAD_IMAGE_AS_POD_SUCCESS'
export const SYNC_UPLOAD_IMAGE_AS_POD_FAILED =
  'yojee/cjf/SYNC_UPLOAD_IMAGE_AS_POD_FAILED'
export const SYNC_UPLOAD_IMAGE_AS_POD_REQUEST =
  'yojee/cjf/SYNC_UPLOAD_IMAGE_AS_POD_REQUEST'

export const SYNC_UPLOAD_IMAGE_AS_SIGNATURE_REQUEST =
  'yojee/cjf/SYNC_UPLOAD_IMAGE_AS_SIGNATURE_REQUEST'
export const SYNC_UPLOAD_IMAGE_AS_SIGNATURE_SUCCESS =
  'yojee/cjf/SYNC_UPLOAD_IMAGE_AS_SIGNATURE_SUCCESS'
export const SYNC_UPLOAD_IMAGE_AS_SIGNATURE_FAILED =
  'yojee/cjf/SYNC_UPLOAD_IMAGE_AS_SIGNATURE_FAILED'

export const SYNC_COMPLETE_TASK_REQUEST = 'yojee/cjf/SYNC_COMPLETE_TASK_REQUEST'
export const SYNC_COMPLETE_TASK_SUCCESS = 'yojee/cjf/SYNC_COMPLETE_TASK_SUCCESS'
export const SYNC_COMPLETE_TASK_FAILED = 'yojee/cjf/SYNC_COMPLETE_TASK_FAILED'

export const PROCESS_CONDITION_OF_RULE_SUCCESS =
  'yojee/cjf/PROCESS_CONDITION_OF_RULE_SUCCESS'

export const SYNC_REPORT_TASK_REQUEST = 'yojee/cjf/SYNC_REPORT_TASK_REQUEST'
export const SYNC_REPORT_TASK_SUCCESS = 'yojee/cjf/SYNC_REPORT_TASK_SUCCESS'
export const SYNC_REPORT_TASK_FAILED = 'yojee/cjf/SYNC_REPORT_TASK_FAILED'
