export const REQUEST_TYPE_UPLOAD_POD = 'UPLOAD_POD'
export const REQUEST_TYPE_UPLOAD_SIGNATURE = 'UPLOAD_SIGNATURE'
export const REQUEST_TYPE_COMPLETE_TASK = 'COMPLETE_TASK'
export const REQUEST_TYPE_REPORT_TASK_DEX = 'REPORT_TASK_DEX'
